version: "3.8"

services:
  ade_reverseproxy:
    # Provides a reverse-proxy to allow hostname-based
    # access to services inside our container network
    image: nginx:latest
    container_name: ade_reverseproxy
    volumes:
      - ./ADE.Local/ADE.ReverseProxy/nginx.conf:/etc/nginx/nginx.conf
      - ./ADE.Local/ADE.ReverseProxy/logs/:/etc/nginx/logs/
    ports:
      - 8080:8080
      - 8888:8888
  ade_apigateway:
    image: ade-apigateway
    container_name: ade_apigateway
    build:
      context: ./ADE.Services/src/
      dockerfile: ./ADE.ApiGateway/Dockerfile
      args:
        - BuildConfiguration
    expose:
      - "80"
    environment:
      - ASPNETCORE_URLS
      - ASPNETCORE_ENVIRONMENT=Development
      - LOGGING__LOGLEVEL__DEFAULT
      - LOGGING__CONSOLE__LOGLEVEL__DEFAULT
      - CONNECTIONS__APIGATEWAYURI
      - CONNECTIONS__BLOBSTORAGECONNECTIONSTRING
      - CONNECTIONS__COSMOSDBCONNECTIONSTRING
      - CONNECTIONS__DATAINGESTORSERVICEURI
      - CONNECTIONS__DATAREPORTERSERVICEURI
      - CONNECTIONS__MARIADBCONNECTIONSTRING
      - CONNECTIONS__POSTGRESQLCONNECTIONSTRING
      - CONNECTIONS__SQLSERVERCONNECTIONSTRING
      - CONNECTIONS__USERSERVICEURI
  ade_frontend:
    image: ade-frontend
    container_name: frontend
    build:
      context: ./ADE.FrontEnd/
      dockerfile: ./Dockerfile
      args:
        - BuildConfiguration
    expose:
      - "80"
    environment:
      - CONNECTIONS__APIGATEWAYURI
  ade_dataingestorservice:
    image: ade-dataingestorservice
    container_name: ade_dataingestorservice
    build:
      context: ./ADE.Services/src/
      dockerfile: ./ADE.DataIngestorService/Dockerfile
      args:
        - BuildConfiguration
    expose:
      - "80"
    environment:
      - ASPNETCORE_URLS
      - ASPNETCORE_ENVIRONMENT=Development
      - LOGGING__LOGLEVEL__DEFAULT
      - LOGGING__CONSOLE__LOGLEVEL__DEFAULT
      - CONNECTIONS__APIGATEWAYURI
      - CONNECTIONS__BLOBSTORAGECONNECTIONSTRING
      - CONNECTIONS__COSMOSDBCONNECTIONSTRING
      - CONNECTIONS__DATAINGESTORSERVICEURI
      - CONNECTIONS__DATAREPORTERSERVICEURI
      - CONNECTIONS__MARIADBCONNECTIONSTRING
      - CONNECTIONS__POSTGRESQLCONNECTIONSTRING
      - CONNECTIONS__SQLSERVERCONNECTIONSTRING
      - CONNECTIONS__USERSERVICEURI
  ade_userservice:
    image: ade-ade_userservice
    container_name: ade_userservice
    build:
      context: ./ADE.Services/src/
      dockerfile: ./ADE.UserService/Dockerfile
      args:
        - BuildConfiguration
    expose:
      - "80"
    environment:
      - ASPNETCORE_URLS
      - ASPNETCORE_ENVIRONMENT=Development
      - LOGGING__LOGLEVEL__DEFAULT
      - LOGGING__CONSOLE__LOGLEVEL__DEFAULT
      - CONNECTIONS__APIGATEWAYURI
      - CONNECTIONS__BLOBSTORAGECONNECTIONSTRING
      - CONNECTIONS__COSMOSDBCONNECTIONSTRING
      - CONNECTIONS__DATAINGESTORSERVICEURI
      - CONNECTIONS__DATAREPORTERSERVICEURI
      - CONNECTIONS__MARIADBCONNECTIONSTRING
      - CONNECTIONS__POSTGRESQLCONNECTIONSTRING
      - CONNECTIONS__SQLSERVERCONNECTIONSTRING
      - CONNECTIONS__USERSERVICEURI
  ade_datareporterservice:
    image: ade-datareporterservice
    container_name: ade_datareporterservice
    build:
      context: ./ADE.Services/src/
      dockerfile: ./ADE.DataReporterService/Dockerfile
      args:
        - BuildConfiguration
    expose:
      - "80"
    environment:
      - ASPNETCORE_URLS
      - ASPNETCORE_ENVIRONMENT=Development
      - LOGGING__LOGLEVEL__DEFAULT
      - LOGGING__CONSOLE__LOGLEVEL__DEFAULT
      - CONNECTIONS__APIGATEWAYURI
      - CONNECTIONS__BLOBSTORAGECONNECTIONSTRING
      - CONNECTIONS__COSMOSDBCONNECTIONSTRING
      - CONNECTIONS__DATAINGESTORSERVICEURI
      - CONNECTIONS__DATAREPORTERSERVICEURI
      - CONNECTIONS__MARIADBCONNECTIONSTRING
      - CONNECTIONS__POSTGRESQLCONNECTIONSTRING
      - CONNECTIONS__SQLSERVERCONNECTIONSTRING
      - CONNECTIONS__USERSERVICEURI
