#
# Module manifest for module 'ADE'
#
# Generated by: brmar
#
# Generated on: 10/12/2020
#

@{
    RootModule        = 'ADE.psm1'
    ModuleVersion     = '1.0.0'
    GUID              = '547BB033-1E18-446D-8BCA-AB0EE94C6389'
    Author            = 'brmar'
    PowerShellVersion = '6.0'
    FunctionsToExport = '*'
    CmdletsToExport   = '*'
    VariablesToExport = '*'
    AliasesToExport   = '*'
    PrivateData       = @{
        PSData = @{}
    }
}