on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
    branches:
      - main
  push:
    branches: 
      - main

name: Build Container Image - ade

jobs:
  build-image:
    name: Build and Publish Image ade
    uses: azuredemoenvironment/ade-app/.github/workflows/build-container-template.yml@main
    with:
      image_to_push: ade
      tag_name: ${GITHUB_REF/refs\/tags\//}
      tag_latest: ${{github.ref == 'refs/heads/main'}}
