name: Run IaC Analysis with PSRule 

on:
  pull_request:
    types:
      - opened
    branches:
      - main
    paths:
      - 'src/bicep/**'
  push:
  workflow_dispatch:


jobs: 
  run-psrule:
    name: Run PSRule analysis
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Scan IaC Templates
      uses: microsoft/ps-rule@main
      with:
        modules: 'PSRule.Rules.CAF'

